name: Publish images

on:
  push:
    branches: master
  schedule:
    - cron: "0 0 * * *"

jobs:
  base-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push opencog-deps to docker hub
        uses: docker/build-push-action@v2
        with:
          context: opencog/base
          tags: ${{ secrets.DOCKER_NAMESPACE }}/opencog-deps:latest
          push: true

      - name: Build and push cogutil to docker hub
        uses: docker/build-push-action@v2
        with:
          context: opencog/cogutil
          tags: ${{ secrets.DOCKER_NAMESPACE }}/cogutil:latest
          push: true

  opencog-dev:
    needs: base-images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: opencog/tools/cli
          tags: |
            ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}:cli
            ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}:latest
          push: true

  moses:
    needs: base-images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: opencog/${{ github.job }}
          tags: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}:latest
          push: true

  postgres:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: opencog/${{ github.job }}
          tags: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}:latest
          push: true

  relex:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: opencog/${{ github.job }}
          tags: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}:latest
          push: true
