name: Publish images

on:
  push:
    branches: master

jobs:
  base-images:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2

      - name: Build and push opencog-deps to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/opencog-deps
          tags: latest
          path: opencog/base

      - name: Build and push cogutil to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/cogutil
          tags: latest
          path: opencog/cogutil

  opencog-dev:
    needs: base-images
    runs-on: ubuntu-20.04
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}
          tags: cli
          path: opencog/tools/cli

  moses:
    needs: base-images
    runs-on: ubuntu-20.04
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}
          tags: latest
          path: opencog/${{ github.job }}

  postgres:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}
          tags: latest
          path: opencog/${{ github.job }}

  relex:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}
          tags: latest
          path: opencog/${{ github.job }}
